USE mydb;

CREATE TABLE club_flairs (
    id INT PRIMARY KEY AUTO_INCREMENT,
    flair_name VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


INSERT INTO club_flairs (flair_name) VALUES

('Computer Science'),
('Engineering'),
('Mathematics'),
('Physics'),
('Chemistry'),
('Biology'),
('Psychology'),
('Economics'),
('Business'),
('Finance'),
('Philosophy'),
('History'),
('Political Science'),
('Sociology'),
('Anthropology'),
('Literature'),
('Languages'),
('Education'),
('Medicine'),
('Law'),
('Architecture'),
('Environmental Science'),
('Neuroscience'),
('Data Science'),
('Statistics'),
('Communications'),
('Marketing'),
('Consulting'),
('Artifical Intelligence'),
('Machine Learning'),
('Cybersecurity'),
('Web Development'),
('Mobile Development'),
('Game Development'),
('Cloud Computing'),
('DevOps'),
('Blockchain'),
('Cryptocurrency'),
('Virtual Reality'),
('Augmented Reality'),
('Internet of Things'),
('Big Data'),
('Robotics'),
('3D Printing'),
('Quantum Computing'),
('Bioinformatics'),
('Genetics'),
('Astronomy'),
('Geology'),
('Meteorology'),
('Oceanography'),
('Zoology'),
('Botany'),
('Ecology'),
('Veterinary Science'),



('Academic'),
('Professional'),
('Cultural'),
('Arts'),
('Music'),
('Theatre'),
('Dance'),
('Sports'),
('Recreation'),
('Social'),
('Community Service'),
('Leadership'),
('Technology'),
('Research'),
('Entrepreneurship'),
('Health & Wellness'),
('Sustainability'),
('International'),
('Religious'),
('Media'),
('Gaming'),
('Outdoors'),
('Hobby'),
('Networking'),
('Competition');